#!/usr/bin/env python3
"""asdf asdfa fd.

asdfasdf
"""

import os
from subprocess import check_call, CalledProcessError
import sys
import yaml

# Load modules from $CHARM_DIR/lib
sys.path.append('lib')
import charms.sshproxy


def build_command(doc):
    """asdf."""
    values = {}
    metrics = doc.get("metrics", {})
    for metric, mdoc in metrics.items():
        cmd = mdoc.get("command")
        if cmd:
            try:
                value, err = charms.sshproxy._run(cmd)
            except CalledProcessError as e:
                continue
            value = value.strip()
            if value:
                values[metric] = value

    if not values:
        return None
    command = ["add-metric"]
    for metric, value in values.items():
        command.append("%s=%s" % (metric, value))
    return command


if __name__ == '__main__':
    charm_dir = os.path.dirname(os.path.abspath(os.path.join(__file__, "..")))
    metrics_yaml = os.path.join(charm_dir, "metrics.yaml")
    with open(metrics_yaml) as f:
        doc = yaml.load(f)
        command = build_command(doc)
        if command:
            check_call(command)
